### ISSUE TITLE
2024 Dec 16 - Protocol Team Checkin

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/pm#12]
Please comment on this issue for things you would like to discuss during the protocol team checkin meeting

**Comment by emhane** [comment]
more labels. definitely labels "contract" and "client" to make distinction if it's a client upgrade or contract upgrade. for client upgrade issues, more labels about what part of the code is effected would be helpful, similar the labels available in reth for example.

**Comment by protolambda** [comment]
For the agenda:

- Big op-geth change for Isthmus: https://github.com/ethereum-optimism/op-geth/pull/451
  - corresponding monorepo change: https://github.com/ethereum-optimism/optimism/pull/12847
- op-geth 1.14.12 update - Proto will update to resolve merge conflicts
  - corresponding monorepo change: https://github.com/ethereum-optimism/optimism/pull/13002
- Flagging so someone (@sebastianst maybe) gets the time to work on this: https://github.com/ethereum-optimism/optimism/issues/13409
  - resolves issue with extra long-range batch submission, that exceeds cache size.
- Ideas how we can close more of the open GH issues / PRs. Too many pages, needs clean up.
- GH release milestones for op-batcher / op-node: delayed for now, Holocene mainnet release was the defining factor last week, no point in off-upgrade-schedule releases now. This may be different after the holidays.
